version: '3.1'

services:
  ucf_db:
    image: postgres:12
    container_name: ucf_db
    restart: always
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=translator
  translator-service:
    image: 'ucf-backend:dev'
    volumes:
      - /srv:/srv/
    container_name: translator-microservice-container
    build:
      context: .
      args:
        - JAR_FILE=build/libs/*
    restart: always
    ports:
      - '8888:8080'
      - '5434:5432'
    depends_on:
      - ucf_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ucf_db:5432/translator
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none